const NOT_STARTED = 'NOT_STARTED';
const PREPARING = 'PREPARING';
const INSTRUCT = 'INSTRUCT';
const READY = 'READY';
const STARTED = 'STARTED';
const ENDED = 'ENDED';
const ALIVE = 'ALIVE';
const DEAD = 'DEAD';
const FINISHED = 'FINISHED';
const PLAYER_JOINED = 'PLAYER_JOINED';
const PLAYER_EXITED = 'PLAYER_EXITED';
const SCORE_BOARD = 'SCORE_BOARD';
const START_GAME = 'START_GAME';
const MAX_ALLOW_PLAYERS = 15;
const MIN_REQD_PLAYERS = 1;
const GAME_TIME = 180000;
const ROW_COUNT = 16;
module.exports = {
    NOT_STARTED,
    PREPARING,
    INSTRUCT,
    READY,
    STARTED,
    ENDED,
    ALIVE,
    DEAD,
    FINISHED,
    PLAYER_JOINED,
    PLAYER_EXITED,
    SCORE_BOARD,
    START_GAME,
    MIN_REQD_PLAYERS,
    MAX_ALLOW_PLAYERS,
    GAME_TIME,
    ROW_COUNT,
};
